package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb
This is a much shorter version ;-) of https://github.com/yast/yast-country/pull/55 and #33.
https://bugzilla.suse.com/show_bug.cgi?id=938951
=> Ensure ntp is installed (when Install Recommended Packages is off)

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/data/ntp_servers.yml
chronos.cru.fr is not realy free accessable: Access policy : accès sous conditions
=> chronos.cru.fr is not realy free accessable: Access policy : accès sous conditions

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/autoyast-rnc/ntpclient.rnc
Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for this module.
=> Fix AutoYaST schema in SLE 12 GA

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/autoyast-rnc/ntpclient.rnc
Merge `sle-12-sp1-after_release` in SP1 branch.
=> Merge post SLE 12 SP1 release changes

Rakefile, package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/autoyast-rnc/ntpclient.rnc
Merge `SLE-12-SP1` branch into `master`.
=> Merge SLE 12 SP1 into master

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, src/modules/NtpClient.rb
The fix was original added here #32, and also added a fix from here #46.
=> Calls to sntp adjusted to the syntax of ntp 4.2.8 (FATE#320392)

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, src/modules/NtpClient.rb
=> Merge changes from GA into SLE-12-SP1 (FATE#320392)

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb
Please review the following changes:
* e1ef35c packaging
* 4991e32 typo
=> [Review] Request from 'schubi2' @ 'yast/yast-ntp-client/review_160811_autoyast_typo'

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/include/ntp-client/widgets.rb
Fix [bsc#1012185](https://bugzilla.suse.com/show_bug.cgi?id=1012185).
=> Fix widget initialization

.rubocop.yml, .travis.yml, package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/lib/cfa/ntp_conf.rb, src/modules/NtpClient.rb, test/cfa/ntp_conf_test.rb, test/fixtures/cfa/ntp.conf, test/ntp_client_test.rb
=> CFA model for ntp conf WIP

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb
Please review the following changes:
* bcefc73 AY: fix crash while writing settings
=> [Review] Request from 'schubi2' @ 'yast/yast-ntp-client/review_170126_ay_write_config'

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/lib/cfa/ntp_conf.rb, src/modules/NtpClient.rb, test/cfa/ntp_conf_test.rb
PBI: https://trello.com/c/7M590k9O/1045-3-sles12-sp3-p1-build-0439-autoyast-installation-crashes-in-ntp
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1045777
=> Fix bug creating restrict records

package/yast2-ntp-client.changes, src/modules/NtpClient.rb, test/fixtures/autoyast/autoinst.xml, test/ntp_client_test.rb
PBI: https://trello.com/c/7M590k9O/1045-3-sles12-sp3-p1-build-0439-autoyast-installation-crashes-in-ntp
=> Avoid sanitize comments

.yardopts, package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/lib/cfa/ntp_conf.rb, src/modules/NtpClient.rb, test/cfa/ntp_conf_test.rb, test/fixtures/autoyast/autoinst.xml, test/ntp_client_test.rb
It merges  #83 #84 #85 and #86 fixes.
=> Merge SLE-12-SP3 into 'master'

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb, test/ntp_client_test.rb
L3: [bsc#1058510](https://bugzilla.suse.com/show_bug.cgi?id=1058510)
https://trello.com/c/NGeTYEgu
=> Avoid Internal Error on Export when fudge records are present

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb, test/ntp_client_test.rb
=> Avoid Internal Error on Export when fudge records are present (master)

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb
Fixes [bsc#1072407](https://bugzilla.suse.com/show_bug.cgi?id=1072407).
=> Fix error message

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/modules/NtpClient.rb
=> Improve ntp error message

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb
=> bsc#1081000: Inform user when NTP server cannot be reached

.gitignore, package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/lib/cfa/ntp_conf.rb, test/cfa/ntp_conf_test.rb, test/fixtures/autoyast/autoinst.xml, test/ntp_client_test.rb, test/test_helper.rb
=> Add support for Tinker Record (bsc#1086526)

Dockerfile, Rakefile
=> Merge SLE-15-GA into master

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, src/modules/NtpClient.rb, test/ntp_client_proposal_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1108497
=> Not write when syncing and save the user status according to the user preferences

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, src/modules/NtpClient.rb, test/ntp_client_proposal_test.rb
=> Merge SLE-12-SP3 into SLE-12-SP4

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/lib/y2ntp_client/widgets/pool_widgets.rb
See https://bugzilla.suse.com/show_bug.cgi?id=1126523 and https://trello.com/c/6boaBrtD/850-translation-bugs-second-wave
=> Add missing textdomain call (bsc#1126523, bsc#1126520) 

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client.rb, src/lib/y2ntp_client/dialog/main.rb
=> Fix "ntp-client" return value for SLE 15 SP1

.rubocop.yml, src/clients/ntp-client.rb, src/clients/ntp-client_auto.rb, src/clients/ntp-client_finish.rb, src/clients/ntp-client_proposal.rb, src/include/ntp-client/commandline.rb, src/include/ntp-client/dialogs.rb, src/include/ntp-client/helps.rb, src/include/ntp-client/misc.rb, src/include/ntp-client/wizards.rb, src/lib/cfa/chrony_conf.rb, src/lib/y2ntp_client/client/auto.rb, src/lib/y2ntp_client/client/finish.rb, src/lib/y2ntp_client/dialog/add_pool.rb, src/lib/y2ntp_client/dialog/main.rb, src/lib/y2ntp_client/widgets/main_widgets.rb, src/lib/y2ntp_client/widgets/pool_widgets.rb, src/modules/NtpClient.rb, test/cfa/chrony_conf_test.rb, test/ntp_client_test.rb, test/test_helper.rb, test/y2ntp_client/widgets/main_widgets_test.rb
needed for https://github.com/yast/yast-ntp-client/pull/151 as ruby without indented heredoc is horrible.
=> New rubocop

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, test/ntp_client_proposal_test.rb
Merge from:
https://github.com/yast/yast-ntp-client/pull/156
=> Master bsc 1164547

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, test/ntp_client_proposal_test.rb
A merge from SLES15-SP1:
https://github.com/yast/yast-ntp-client/pull/158
=> Master bsc 1164547 b

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb
This is a merge from SLES15-SP1:
https://github.com/yast/yast-ntp-client/pull/160
=> Master bsc 1164547 c

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, test/ntp_client_proposal_test.rb
=> Fix ntp servers call in SLE-15-SP2

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, test/ntp_client_proposal_test.rb
It merges #168 into SLE-15-SP3
=> Merge SLE-15-SP2 into SLE-15-SP3

package/yast2-ntp-client.changes, package/yast2-ntp-client.spec, src/clients/ntp-client_proposal.rb, src/modules/NtpClient.rb, test/ntp_client_proposal_test.rb, test/ntp_client_test.rb, test/y2ntp_client/client/auto_test.rb
Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.
=> Use `Package` instead of `PackageSystem`
