yast/yast-ntp-client

package/yast2-ntp-client.changes
src/autoyast-rnc/ntpclient.rnc

Fixes [bsc#954412](https://bugzilla.suse.com/show_bug.cgi?id=954412) for SLE 12 SP1. BTW, `SLE-12-GA` branch is merged into `sle-12-sp1-after_release`.

Fix AutoYaST schema SLE12 SP1

---

.gitignore
package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
src/include/ntp-client/dialogs.rb
src/include/ntp-client/helps.rb
src/include/ntp-client/widgets.rb
src/modules/NtpClient.rb

Originally I wanted to simply fix a trivial [bug 978453](https://bugzilla.suse.com/show_bug.cgi?id=978453) - the default value in the help text did not match the value in the UI, but after looking into it I found several hidden skeletons or zombies...
- Unify the default value in the code (BTW the proposal client used   a different default)
- Set the initial state of the interval widget according to the current synchronization mode
- Fixed firewall widget layout (double frame widget)
- 3.1.23
Here are the screenshots showing the fixes in the UI.
After starting the module the *Inverval of the Synchronization in Minutes* widget was enabled although the initial start mode was *Now and on Boot*. The setting makes sense only in the *Synchronize without Daemon* mode.
If you change the mode to …

Fixed the default synchronization interval in the help text (bsc#978453)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
src/modules/NtpClient.rb

I have updated the syntax of sntp call, but also we check now if the server is not reachable checking the presence of "lookup error" in the stderr **[[1]]**.
I added this check because sntp always returns 0 although the server is not answering or not reachable, so the current NTP Test is useless.
We could do more checks like for example check if stdout includes "no UCST reponse" **[[2]]** and maybe other checks, but i'm afraid the answer could change or be very dependent of current responses what could need updates each time the response changes but on the other hand this is only a Test functionality and for this reason not a critical one.
[1]: https://github.com/ntp-project/ntp/blob/1a399a03e674da08cfce2cdb847bfb65d65df237/sntp/main.c#L461
[2]: …

Calls to sntp adjusted to syntax from ntp 4.2.8 (bsc#979421)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/modules/NtpClient.rb

If nil comments are given then an empty server entry will be written to /etc/ntp.conf

Convert ntp record's comment to string to avoid nil values (bsc#977610)

---

.travis.sh
.travis.yml
Dockerfile
package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
test/cfa/ntp_conf_test.rb
test/ntp_client_test.rb

Just fixed some tests that does not allow to build the package correctly. Travis does not complain because it uses the old ntp.lense
Josef Reidinger fixed the ntp lense in this commit:
hercules-team/augeas@01e4c42
Basically before the fix it doesn't expect to have restrict records with IPv4 explicitly, as for example:
`restrict -4 default`
So before the fix `-4` was treated as an **address** and `default` as an **option* what is wrong.
With the new lense, **cfa** will read the **IP version** correctly.
**IN PROCCESS**
```
The ubuntu repository for augeas is ppa:raphink/augeas, which installs:
Setting up augeas-lenses (1.4.0-0ubuntu1~augeas1~precise4) ...
Setting up libaugeas0 (1.4.0-0ubuntu1~augeas1~precise4) ...
```
We need updated packages.

Fixed some tests (bsc#983486).

---

.travis.yml
Rakefile
package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/lib/cfa/ntp_conf.rb
test/cfa/ntp_conf_test.rb
test/fixtures/cfa/ntp.conf

NtpClient does not handle the configuration file properly. The problem is fixed in `master`, but we need to fix also for CaaSP. So I've decided to port (actually to copy) the CFA class (used in master).
This class won't be used by `NtpClient` as there are too many changes involved and I would like to be as conservative as possible at this point.
Of course, CaaSP version will diverge from SLE 12 SP2.

Add CFA class

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/modules/NtpClient.rb

Trello card: https://trello.com/c/N9tffDE4/1062-sles12-sp2-p3-983486-yast2-ntp-client-mangles-etc-ntpconf
Default template is something like:
```
restrict -4 default notrap...
restrict -6 default notrap...
pool.ntp.example.org
```
And after read and write it was written as:
```
pool.ntp.example.org
restrict -4 default notrap...
restrict -6 default notrap...
```
This PR just writes the restrict entries before the rest.

Write restrict records first (bsc#983486)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/autoyast-rnc/ntpclient.rnc

- https://bugzilla.suse.com/show_bug.cgi?id=1013047

Permitted the use of 'listentry' element or 'ntp_server' and to be an empty list

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
test/ntp_client_proposal_test.rb

Related to https://bugzilla.suse.com/show_bug.cgi?id=1075039
---
Despite user unchecks "Run NTP as daemon", the chronyd service keeps active and enabled.
It seems that the timezone dialog (_yast-country_) is missing the `run_service` param at the time to call the `NtpClientProposalClient#Write` (_yast-ntp-client_). See [yast-country/timezone/src/include/timezone/dialogs.rb:L980](https://github.com/yast/yast-country/blob/a575e590d60657b028bc2003964ec158285618d1/timezone/src/include/timezone/dialogs.rb#L980).
In consequence, [since the default value for that param is `true`](https://github.com/yast/yast-ntp-client/blob/6d99c3d88a49f5f83e3053c215259e479b6db2c2/src/clients/ntp-client_proposal.rb#L345), the service is being started and enabled always, without matter what the user has chosen. …

Save the chronyd service according to user preference

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
src/modules/NtpClient.rb
test/ntp_client_proposal_test.rb

It basically backports yast/yast-ntp-client#116 which was backported into SLE-12-SP3 in forward and also a fix for not writing when "synchronize" is called.

Merge SLE-12-SP4 into SLE-15-GA

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb

Fix for [bsc#1039985](https://bugzilla.suse.com/show_bug.cgi?id=1039985), in previous attempt [bsc#893065](https://bugzilla.suse.com/show_bug.cgi?id=893065) it was fixed in SLE but broken in openSUSE.

Only sync ui

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/modules/NtpClient.rb
test/ntp_client_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1108497
There is an error in the return code as the path is `bash` and not `bash_output`
This PR just fix that.

Fix return code

---

test/ntp_client_test.rb

Merge SLE-15-GA into master

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/lib/cfa/ntp_conf.rb
src/modules/NtpClient.rb
test/cfa/ntp_conf_test.rb

For https://trello.com/c/GA5jJ2a7/1188-3-sles12-sp5-p2-1142026-augeas-parsing-serializing-error-when-ntp-client-configuration-is-specified-in-autoyast-control-file.

Fixed saving /etc/ntp.conf with certain comments (bsc#1142026)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/lib/cfa/ntp_conf.rb
src/modules/NtpClient.rb
test/cfa/ntp_conf_test.rb
test/fixtures/autoyast/autoinst.xml
test/ntp_client_test.rb

When an imported AutoYaST profile specifies an NTP entry where the comment contains empty lines, the Augeas parser fails when trying to save the `/etc/ntp.conf` file.
```
<peer>
<address>1.opensuse.pool.ntp.org</address>
<comment> # a comment with spaces
</comment>
<options>iburst</options>
<type>server</type>
</peer>
```
*  https://bugzilla.suse.com/show_bug.cgi?id=1142026
This was already fixed by https://github.com/yast/yast-ntp-client/pull/143. IMHO, the problem with that solution is that we are delegating the responsibility of fixing the imported record to the method `NtpConf#save`.
This new solution moves such responsibility to the `sanitizer` method that already exists. This sanitizer is called during the AutoYaST importation. 
* Added unit tests
* Manually tested

AutoYaST: sanitize comments when importing

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec

https://bugzilla.suse.com/show_bug.cgi?id=1160890
https://trello.com/c/3Y9HSV8m
`/bin/systemctl` symlink is gone.
Don't use it.

don't use /bin/systemctl compat symlink (bsc#1160890)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
src/lib/y2ntp_client/widgets/pool_widgets.rb
src/modules/NtpClient.rb
test/data/ntp_servers_sample.yml
test/ntp_client_proposal_test.rb
test/ntp_client_test.rb
test/test_helper.rb

Use the new `Y2Network::NtpServer` when proposing the default values for NTP servers.
Related PR: https://github.com/yast/yast-network/pull/1039

[SLE-7188] Default to SUSE NTP servers

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
test/ntp_client_proposal_test.rb

**Problem**
The user can select **one** server in the time setting module and can switch to the ntp client module in order to add/update additional one. So the settings/views in both screen are not compatible together.
**Solution**
If more than one ntp server has configured in the ntp client they will be only shown in the time setting screen
**Testing**
Manuel testing. Adapting test cases.

Supporting more than one ntp server in the time setting module.

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/autoyast-rnc/ntpclient.rnc

trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886

Schema change

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/clients/ntp-client_proposal.rb
test/ntp_client_proposal_test.rb

The Timezone Dialog crashes when the ntp proposal client returns some NtpServer.
- https://bugzilla.suse.com/show_bug.cgi?id=1185545
Adapted the code to the changes introduced by https://github.com/yast/yast-network/pull/1039 returning an array of strings instead of NtpServer objects.

Fix proposal dhcp_ntp_servers call

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
test/test_helper.rb

- Use the new YaST RSpec helper everywhere

Unify YaST module mocking in unit tests

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/modules/NtpClient.rb
test/ntp_client_test.rb
test/y2ntp_client/client/auto_test.rb

During installation, we try to call **netconfig** for writing and updating the ntp policy even when **netconfig** it is not available.
- [bsc#1198066](https://bugzilla.suse.com/show_bug.cgi?id=1198066)
Skip netconfig configuration if it is not available
- *Added a new unit test*

Skip netconfig configuration when it is not available (bsc#1198066)

---

package/yast2-ntp-client.changes
package/yast2-ntp-client.spec
src/modules/NtpClient.rb

In #174 we fixed a Tumbleweed bug avoiding to call **netconfig** when it was not present in the system but as consequence of that bug the executable is probably not called anymore in **SLE-15-SP5** as we modified the full path of the executable to be **/usr/sbin/netconfig** which is wrong as it should be **/sbin/netconfig**.
- [*bsc#1205401*](https://bugzilla.suse.com/show_bug.cgi?id=1205401)
Fix the **netconfig full path** in **SLE-15-SP5** by now although we should look for a better solution in order to not use full paths anymore avoiding these kinds of problems **(usr-merge)**.

Fix netconfit path
